[workspace]
members = [".", "conformance"]

[package]
name = "phig"
description = "Parser and serializer for phig"
version = "0.4.1"
edition = "2021"
license = "MIT"

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1", optional = true }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
